#!/bin/bash
#
echo -n "Sisesta kuu number: "
read kuu
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then
echo "on talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
echo "on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
echo "on suvi"
elif test
$kuu -ge 9 -a $kuu -le 11
then
echo "on sügis"
else
echo "kuud pole olemas"
fi
