#!/bin/bash
#
#Reisi päevade kalkulatsioon
echo "Pühapäev (0), Esmaspäev (1), Teisipäev (2), Kolmapäev (3), Neljapäev (4), Reede (5), Laupäev (6)"
echo "Vali numbritest millisel nädalapäeval reisile minnakse: "
read a
echo "Mitu ööpäeva reisil ollakse: "
read b
c=$(($a + $b))
tagasi=$(($c %7))
echo "Tagasi oled päeval numbriga $tagasi "
#
#lõpp
