#!/bin/bash
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tärnide arv reas: "; read tarn
reanum=1

for (( i = 1; i <= $rida; i++ ))
do
echo -n "$reanum"
let reanum++
for (( j = 1; j <= $tarn; j++ ))
do
echo -n "* "
done
echo ""
done
