#!/bin/bash
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tärnide arv reas: "; read tarn
reanum=1

for (( i =1; i <= $ridu; i++ ))
do
echo -n "$reanum"
let reanum++
for (( j = 1; j <= $tarn; j++ ))
do
if (($i == 1 || $i == $rida)); then
echo -n "* "
elif (($j == 1 || $j == $tarn)); then
echo -n "* "
else
echo -n " "
fi
done
echo ""
done
